Реализовано каскадное удаление, в сервисах попробовал исправить метод…
kyd3snik/travel pull request #16
Opened 2020-06-05 16:51 UTC by Alexandr-01

…ы получения по id, а также методы update. в сервисе курорта при получении доступных курортов добавил проверку на дату (подходят только те курорты, которые еще не начались)

2020-06-05 17:10 UTC, kartashovaa requested changes

2020-06-05 17:10 UTC, kartashovaa commented on src/main/java/com/kyd3snik/travel/services/CityService.java
> +        throwIfCantDelete(user, getById(id), resortService.findByArrivalCity(city),
Нинада так, верни как было, было читабельнее
Еще у тебя getById 2 раза вызывается

2020-06-05 17:10 UTC, kyd3snik commented on src/main/java/com/kyd3snik/travel/services/CountryService.java
> +        if (country.isPresent())
там есть метод orElseThrow, и это все сокращается до 
return countryRepository.findById(id).orElseThrow(), но лучше
return countryRepository.findById(id).orElseThrow(() -> new IllegalStateException("Тут текст ошибки"))

2020-06-05 17:10 UTC, kyd3snik commented on src/main/java/com/kyd3snik/travel/services/HotelService.java
> +        throwIfCantDelete(user, resortService.findByHotel(getById(id)));
Не надо так сокращать, код менее читабельный

2020-06-05 17:14 UTC, Alexandr-01 commented on src/main/java/com/kyd3snik/travel/services/CityService.java
> +        throwIfCantDelete(user, getById(id), resortService.findByArrivalCity(city),
Хорошо, я изначально думал, что это плохая идея, но что-то нехорошее меня потянуло за руку))

2020-06-05 20:45 UTC, kartashovaa requested changes

2020-06-05 20:45 UTC, kyd3snik commented on src/main/java/com/kyd3snik/travel/services/CountryService.java
> +        throwIfCantDelete(user, userService.getAll(), cities, resortsArrival, resortsDeparture);
По идее, этот метод теперь бесполезный, так как связи настроены
Можешь это потестить, попробуй удалить страну, к которой привязан какой-нибудь параметр метода, например пользователь, если  все ок, то база должна кинуть исключение

2020-06-05 20:45 UTC, kyd3snik commented on src/main/java/com/kyd3snik/travel/services/ResortService.java
> +                .filter(resort -> !resort.getStartDate().before(DateUtil.getToday()))
Условия с отрицанием читаются сложнее, в данном случае можно заменить на DateUtil.getToday().after(resort.getStartDate())

2020-06-05 20:45 UTC, kyd3snik commented on src/main/java/com/kyd3snik/travel/controller/HotelController.java
> +        hotelService.addHotel(new Hotel(0, title, city, address, stars, new ArrayList<HotelRoom>(), Collections.emptyList()));
Раз уж тебе все равно править ПР, замени тут `new ArrayList<HotelRoom>()` на `Collections.emptyList()` для единообразия)

2020-06-06 01:22 UTC, Alexandr-01 commented on src/main/java/com/kyd3snik/travel/services/CountryService.java
> +        throwIfCantDelete(user, userService.getAll(), cities, resortsArrival, resortsDeparture);
мне кажется, что стоит оставить этот метод, т.к. он более четко обозначает ошибку

2020-06-06 08:31 UTC, kyd3snik commented on src/main/java/com/kyd3snik/travel/services/CountryService.java
> +        throwIfCantDelete(user, userService.getAll(), cities, resortsArrival, resortsDeparture);
Ну её знаю, каким образом? Тем что ошибку кидает не база, а ты? Тем более он максимально медленно работает. Ты тут тянешь всех пользователей, города, для каждого города курорты, это очень много данных.

2020-06-06 17:10 UTC, merged